services:
  - type: web
    name: genetic-disorder-backend
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

  - type: web
    name: genetic-disorder-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "./frontend/dist"
